apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: railstest
    name: railstest
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 9876-tcp
      port: 9876
      protocol: TCP
      targetPort: 9876
    selector:
      app: railstest
      deploymentconfig: railstest
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 2000s
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: railstest
    name: railstest
  spec:
    host: railstest-dltp-1066-container-spike.192.168.99.100.nip.io
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: railstest
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2017-10-12T15:55:45Z
        status: "True"
        type: Admitted
      host: railstest-dltp-1066-container-spike.192.168.99.100.nip.io
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: railstest
    name: railstest
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/dltp-1066-container-spike/railstest:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: railstest
    name: railstest
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: railstest:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/jgondron/oshifted_api.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: RAILS_ENV
          value: development
        from:
          kind: ImageStreamTag
          name: ruby:2.3
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: 8leb_CHEBNHgXuWH2BsT
      type: GitHub
    - generic:
        secret: q57zbYSR027lH7y3EVhi
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: railstest
    name: railstest
  spec:
    replicas: 1
    selector:
      app: railstest
      deploymentconfig: railstest
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: railstest
          deploymentconfig: railstest
      spec:
        containers:
        - args:
          - -c
          - bundle exec rails server
          command:
          - bash
          env:
          - name: RAILS_ENV
            value: development
          - name: SECRET_KEY_BASE
            value: 39442fb448c0059e9a7ef1bc39c8b9b8411cac2cb2a5a28ec6cfd071508335ee1dd88520b323ee06fa19c07c23510503ea203bfe8ce165200e7f72030bad8c6d
          - name: WEB_CONCURRENCY
            value: "0"
          image: 172.30.1.1:5000/dltp-1066-container-spike/railstest@sha256:1d5ca5e3e175d1c2af0447925cf1afc3e9a2084638bf6025c5acaa80102ee7b8
          imagePullPolicy: Always
          name: railstest
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - railstest
        from:
          kind: ImageStreamTag
          name: railstest:latest
          namespace: dltp-1066-container-spike
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
